# Hadolint configuration for Entynet Enterprise
failure-threshold: warning

ignored:
  - DL3008  # Pin versions in apt get install
  - DL3015  # Avoid additional packages by specifying `--no-install-recommends`
  - DL3059  # Multiple consecutive `RUN` instructions. Consider consolidation.
  - DL4006  # Set the `SHELL` to `/bin/bash`

override:
  error:
    - DL3018
    - DL3023
  warning:
    - DL3003
    - DL3004
  info:
    - DL3007
    - DL3013
  style:
    - DL3005
    - DL3006
